name: mlflow-project-env
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - mlflow==3.8.0
      - pandas
      - numpy
      - scikit-learn
      - matplotlib
      - joblib