name: MLflow Retraining CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.10

      - name: Install MLflow
        run: |
          pip install mlflow

      - name: Run MLflow Project (retrain model)
        run: |
          mlflow run MLProject